#
# .travis.yml
# iina
#

# Enviornment
language: swift
osx_image: xcode10
os: osx

env:
    global:
        - LANG=en_US.UTF-8
        - LC_ALL=en_US.UTF-8
        - LANGUAGE=en_US.UTF-8

# CocoaPods
before_install:
    - env
    - locale
    - gem install cocoapods -v 1.6.0.beta.2 --no-rdoc --no-ri --no-document --quiet
    - pod install

# Build Jobs
script:
    # Clean
    - xcodebuild clean
    # IINA main app
    - xcodebuild -workspace iina.xcworkspace -scheme iina
    # IINA cli
    - xcodebuild -workspace iina.xcworkspace -scheme iina-cli

# After Build
notifications:
    email: false